// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: VolumeKnobGUI

#include "../ui.h"

void ui_SongControls_screen_init(void)
{
    ui_SongControls = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SongControls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SongControls, lv_color_hex(0x583E5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SongControls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicArtwork = lv_obj_create(ui_SongControls);
    lv_obj_remove_style_all(ui_MusicArtwork);
    lv_obj_set_width(ui_MusicArtwork, 145);
    lv_obj_set_height(ui_MusicArtwork, 145);
    lv_obj_set_x(ui_MusicArtwork, -90);
    lv_obj_set_y(ui_MusicArtwork, -60);
    lv_obj_set_align(ui_MusicArtwork, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MusicArtwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicArtwork, lv_color_hex(0x801F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicArtwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Artist = lv_label_create(ui_SongControls);
    lv_obj_set_width(ui_Artist, 169);
    lv_obj_set_height(ui_Artist, 20);
    lv_obj_set_x(ui_Artist, 243);
    lv_obj_set_y(ui_Artist, 109);
    lv_label_set_long_mode(ui_Artist, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Artist, "Artist\n");
    lv_obj_set_style_text_color(ui_Artist, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Artist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Artist, &ui_font_monsterrat_semibold_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SongName = lv_label_create(ui_SongControls);
    lv_obj_set_width(ui_SongName, 190);
    lv_obj_set_height(ui_SongName, 70);
    lv_obj_set_x(ui_SongName, 243);
    lv_obj_set_y(ui_SongName, 140);
    lv_label_set_long_mode(ui_SongName, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_SongName, "Song Name");
    lv_obj_set_style_text_color(ui_SongName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SongName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SongName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SongName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SongName, &ui_font_monsterrat_semibold_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Source = lv_label_create(ui_SongControls);
    lv_obj_set_height(ui_Source, 24);
    lv_obj_set_width(ui_Source, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Source, 275);
    lv_obj_set_y(ui_Source, 223);
    lv_label_set_long_mode(ui_Source, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Source, "Echo Show 15");
    lv_obj_set_style_text_color(ui_Source, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Source, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Source, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Source, &ui_font_monsterrat_semibold_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Source, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Source, lv_color_hex(0x696969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Source, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Source, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Source, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Source, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Source, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowerPanel = lv_obj_create(ui_SongControls);
    lv_obj_set_width(ui_LowerPanel, 492);
    lv_obj_set_height(ui_LowerPanel, 196);
    lv_obj_set_x(ui_LowerPanel, 0);
    lv_obj_set_y(ui_LowerPanel, 148);
    lv_obj_set_align(ui_LowerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LowerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LowerPanel, lv_color_hex(0x473249), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LowerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LowerPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SongProgressBar = lv_bar_create(ui_SongControls);
    lv_bar_set_value(ui_SongProgressBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SongProgressBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SongProgressBar, 480);
    lv_obj_set_height(ui_SongProgressBar, 3);
    lv_obj_set_x(ui_SongProgressBar, 0);
    lv_obj_set_y(ui_SongProgressBar, 50);
    lv_obj_set_align(ui_SongProgressBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SongProgressBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SongProgressBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SongProgressBar, 76, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SongProgressBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SongProgressBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ButtonPlayPause = lv_imgbtn_create(ui_SongControls);
    lv_imgbtn_set_src(ui_ButtonPlayPause, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_play_png, NULL);
    lv_imgbtn_set_src(ui_ButtonPlayPause, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_pause_png, NULL);
    lv_obj_set_width(ui_ButtonPlayPause, 48);
    lv_obj_set_height(ui_ButtonPlayPause, 48);
    lv_obj_set_x(ui_ButtonPlayPause, 0);
    lv_obj_set_y(ui_ButtonPlayPause, 110);
    lv_obj_set_align(ui_ButtonPlayPause, LV_ALIGN_CENTER);

    ui_ButtonBack = lv_imgbtn_create(ui_SongControls);
    lv_imgbtn_set_src(ui_ButtonBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
    lv_obj_set_width(ui_ButtonBack, 48);
    lv_obj_set_height(ui_ButtonBack, 48);
    lv_obj_set_x(ui_ButtonBack, -78);
    lv_obj_set_y(ui_ButtonBack, 110);
    lv_obj_set_align(ui_ButtonBack, LV_ALIGN_CENTER);

    ui_ButtonShuffle = lv_imgbtn_create(ui_SongControls);
    lv_imgbtn_set_src(ui_ButtonShuffle, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_shuffle_png, NULL);
    lv_imgbtn_set_src(ui_ButtonShuffle, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_236185509, NULL);
    lv_obj_set_width(ui_ButtonShuffle, 48);
    lv_obj_set_height(ui_ButtonShuffle, 48);
    lv_obj_set_x(ui_ButtonShuffle, -148);
    lv_obj_set_y(ui_ButtonShuffle, 110);
    lv_obj_set_align(ui_ButtonShuffle, LV_ALIGN_CENTER);

    ui_ButtonNext = lv_imgbtn_create(ui_SongControls);
    lv_imgbtn_set_src(ui_ButtonNext, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_forward_png, NULL);
    lv_obj_set_width(ui_ButtonNext, 48);
    lv_obj_set_height(ui_ButtonNext, 48);
    lv_obj_set_x(ui_ButtonNext, 78);
    lv_obj_set_y(ui_ButtonNext, 110);
    lv_obj_set_align(ui_ButtonNext, LV_ALIGN_CENTER);

    ui_ButtonRepeat = lv_imgbtn_create(ui_SongControls);
    lv_imgbtn_set_src(ui_ButtonRepeat, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1640048024, NULL);
    lv_imgbtn_set_src(ui_ButtonRepeat, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_852668713, NULL);
    lv_obj_set_width(ui_ButtonRepeat, 48);
    lv_obj_set_height(ui_ButtonRepeat, 48);
    lv_obj_set_x(ui_ButtonRepeat, 148);
    lv_obj_set_y(ui_ButtonRepeat, 110);
    lv_obj_set_align(ui_ButtonRepeat, LV_ALIGN_CENTER);

    ui_DisplaySource = lv_img_create(ui_SongControls);
    lv_img_set_src(ui_DisplaySource, &ui_img_sourcespotify_png);
    lv_obj_set_width(ui_DisplaySource, 24);
    lv_obj_set_height(ui_DisplaySource, 24);
    lv_obj_set_x(ui_DisplaySource, 243);
    lv_obj_set_y(ui_DisplaySource, 223);
    lv_obj_add_flag(ui_DisplaySource, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DisplaySource, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ButtonPlayPause, btn_event_cb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBack, btn_event_cb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonNext, btn_event_cb, LV_EVENT_ALL, NULL);

}
