// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: VolumeKnobGUI

#include "../ui.h"

void ui_VolumeKnob_screen_init(void)
{
    ui_VolumeKnob = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_VolumeKnob, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VolumeKnob, lv_color_hex(0x583E5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeKnob, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_VolumeKnob);
    lv_obj_set_width(ui_Arc1, 452);
    lv_obj_set_height(ui_Arc1, 452);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);
    lv_arc_set_bg_angles(ui_Arc1, 116, 64);
    lv_obj_set_style_arc_width(ui_Arc1, 44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Arc1, &ui_img_272761352, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc1, 43, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Arc1, &ui_img_671809700, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Arc1, &ui_img_indicator_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Arc1, 6, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Arc1, 38, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_VolumeCount = lv_label_create(ui_VolumeKnob);
    lv_obj_set_width(ui_VolumeCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VolumeCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VolumeCount, 0);
    lv_obj_set_y(ui_VolumeCount, 11);
    lv_obj_set_align(ui_VolumeCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolumeCount, "99");
    lv_obj_set_style_text_color(ui_VolumeCount, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolumeCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VolumeCount, &ui_font_monsterrat_bold_148, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_VolumeKnob);
    lv_img_set_src(ui_Image1, &ui_img_sourcespotifylarge_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 146);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
