// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: VolumeKnobGUI

#include "../ui.h"


// COMPONENT MusicArtwork

lv_obj_t * ui_MusicArtwork_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_MusicArtwork;
    cui_MusicArtwork = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_MusicArtwork);
    lv_obj_set_width(cui_MusicArtwork, 145);
    lv_obj_set_height(cui_MusicArtwork, 145);
    lv_obj_set_x(cui_MusicArtwork, -90);
    lv_obj_set_y(cui_MusicArtwork, -60);
    lv_obj_set_align(cui_MusicArtwork, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_MusicArtwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_MusicArtwork, lv_color_hex(0x801F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_MusicArtwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MUSICARTWORK_NUM);
    children[UI_COMP_MUSICARTWORK_MUSICARTWORK] = cui_MusicArtwork;
    lv_obj_add_event_cb(cui_MusicArtwork, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_MusicArtwork, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_MusicArtwork_create_hook(cui_MusicArtwork);
    return cui_MusicArtwork;
}

