// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: VolumeKnobGUI

#ifndef _UI_COMP_MUSICARTWORK_H
#define _UI_COMP_MUSICARTWORK_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MusicArtwork
#define UI_COMP_MUSICARTWORK_MUSICARTWORK 0
#define _UI_COMP_MUSICARTWORK_NUM 1
lv_obj_t * ui_MusicArtwork_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
